name: sqflite_simple_dao_backend
description: A new Flutter package project.
homepage: https://github.com/Necro-Coder/sqflite_simple_dao_backend
version: 1.0.1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  meta: ^1.9.1
  reflectable: ^4.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15
  logger: ^2.0.2+1
  mockito: ^5.4.4
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  test: ^1.24.9
