name: sqflite_simple_dao_backend
description: A new Flutter package project.
version: 0.0.1
author: Ruben Nunez Cotano

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  meta: ^1.9.1
  reflectable: ^4.0.5
  sqflite: ^2.2.8+4
  path_provider: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
